"""Pydantic models defining the public API contracts.

These are the request/response shapes shown in Swagger and validated
automatically by FastAPI.
"""

from pydantic import BaseModel, Field


class UploadResponse(BaseModel):
    """Returned by POST /upload after a document is processed and indexed."""

    doc_id: str = Field(description="Short unique id assigned to the document")
    filename: str = Field(description="Original uploaded filename")
    category: str = Field(description="Category assigned by Agent 1")
    summary: str = Field(description="2-3 sentence summary from Agent 1")
    topics: list[str] = Field(description="Key topics detected by Agent 1")
    chunks_indexed: int = Field(description="Number of chunks stored in FAISS")
    status: str = Field(default="indexed", description="Processing status")


class AskRequest(BaseModel):
    """Body of POST /ask."""

    question: str = Field(
        min_length=1,
        description="Natural-language question about the uploaded documents",
        examples=["What skills are listed in the resume?"],
    )
    doc_id: str | None = Field(
        default=None,
        description="Optional: restrict the answer to one document",
    )
    session_id: str = Field(
        default="default",
        max_length=64,
        pattern=r"^[A-Za-z0-9_.:-]+$",
        description="Conversation session id (<=64 chars, alnum/_.:- only); "
        "follow-up questions in the same session use chat history for context",
    )
    screen_context: dict | None = Field(
        default=None,
        description=(
            "Optional screen analysis from POST /screen/analyze; when "
            "attached, the answer can reference what is currently on the "
            "user's screen (keys like application, summary, detected_text)"
        ),
    )


class Source(BaseModel):
    """One supporting passage used to ground the answer."""

    filename: str = Field(description="Document the passage came from")
    page: int | None = Field(default=None, description="Page number (PDFs only)")
    snippet: str = Field(description="Excerpt of the supporting text")


class ValidationInfo(BaseModel):
    """Agent 3's verdict on the generated answer."""

    checked: bool = Field(description="Whether validation ran for this answer")
    supported: bool = Field(
        default=True, description="True if the answer is grounded in the context"
    )
    confidence: str = Field(
        default="unknown", description="Validator confidence: high/medium/low"
    )


class AutomationInfo(BaseModel):
    """Agent 6's execution record for an automation request."""

    action: str = Field(
        description="Executed action: email_draft, export_summary, action_plan"
    )
    status: str = Field(description="completed or failed")
    file: str | None = Field(
        default=None, description="Generated file in the exports directory"
    )
    download_url: str | None = Field(
        default=None, description="Relative URL to download the generated file"
    )
    extra: dict = Field(
        default_factory=dict,
        description="Action-specific details (e.g. mailto link, subject)",
    )


class ExportFileInfo(BaseModel):
    """One generated file, as listed by GET /exports."""

    filename: str
    size_bytes: int
    modified: str


class ExportsResponse(BaseModel):
    """Returned by GET /exports."""

    files: list[ExportFileInfo]


class IntentInfo(BaseModel):
    """Agent 5's verdict: what the user wants and how to fulfil it."""

    intent: str = Field(
        description=(
            "Detected intent: question_answering, summarization, "
            "screen_help, automation, email, export, search, navigation "
            "or classification"
        )
    )
    confidence: float = Field(description="Detector confidence, 0.0-1.0")
    recommended_workflow: str = Field(
        description="Workflow that should fulfil this intent"
    )
    method: str = Field(
        description="How the intent was detected: heuristic, llm, or fallback"
    )


class IntentDetectRequest(BaseModel):
    """Body of POST /intent/detect."""

    question: str = Field(
        min_length=1,
        description="The user request to classify",
        examples=["Draft an email to HR about my interview"],
    )
    screen_context: dict | None = Field(
        default=None,
        description="Optional screen analysis from POST /screen/analyze",
    )


class WorkflowStageInfo(BaseModel):
    """Execution record of one workflow pipeline stage."""

    name: str = Field(
        description="Stage name: observe, understand, analyze, guide, automate"
    )
    status: str = Field(description="completed, skipped, or failed")
    duration_ms: float = Field(description="Stage execution time in milliseconds")


class AskResponse(BaseModel):
    """Returned by POST /ask."""

    answer: str = Field(description="Grounded answer generated by Agent 2")
    routed_document: str | None = Field(
        default=None,
        description="Filename Agent 2 routed the question to (None = all documents)",
    )
    sources: list[Source] = Field(description="Supporting passages")
    found: bool = Field(
        description="False when the answer is not present in the documents"
    )
    validation: ValidationInfo = Field(
        default_factory=lambda: ValidationInfo(checked=False),
        description="Agent 3 grounding verdict",
    )
    workflow: list[WorkflowStageInfo] = Field(
        default_factory=list,
        description=(
            "Trace of the Observe -> Understand -> Analyze -> Guide -> "
            "Automate pipeline that produced this answer"
        ),
    )
    intent: IntentInfo | None = Field(
        default=None,
        description="Agent 5's intent verdict for this request",
    )
    automation: AutomationInfo | None = Field(
        default=None,
        description="Agent 6's execution record, present for automation intents",
    )


class TranscribeResponse(BaseModel):
    """Returned by POST /speech/transcribe."""

    text: str = Field(description="Transcribed speech (empty for silence)")


class ScreenAnalyzeResponse(BaseModel):
    """Returned by POST /screen/analyze -- Agent 4's screen understanding."""

    application: str = Field(
        description="Application or website detected on screen"
    )
    activity: str = Field(
        description="One sentence describing what the user is doing"
    )
    detected_text: str = Field(
        description="The most important text visible on the screen"
    )
    summary: str = Field(
        description="2-3 sentence summary of what is happening on screen"
    )
    user_intent: str = Field(
        description="The user's most likely goal right now"
    )
    suggested_actions: list[str] = Field(
        description="Concrete next actions the user could take"
    )
    analysis_method: str = Field(
        description=(
            "Which pipeline produced this result: 'gemini_vision' (primary), "
            "'ocr_llm' (OCR text interpreted by the LLM), or 'ocr_only' "
            "(raw OCR text, all AI providers unavailable)"
        )
    )


class DocumentInfo(BaseModel):
    """One indexed document, as listed by GET /documents."""

    doc_id: str
    filename: str
    category: str
    summary: str
    chunks: int


class DocumentsResponse(BaseModel):
    """Returned by GET /documents."""

    documents: list[DocumentInfo]


class DeleteDocumentResponse(BaseModel):
    """Returned by DELETE /documents/{doc_id}."""

    doc_id: str = Field(description="Id of the removed document")
    status: str = Field(default="deleted", description="Removal status")


class HealthResponse(BaseModel):
    """Returned by GET /health."""

    status: str = Field(description="Service status")
    documents_indexed: int = Field(description="Documents currently in the index")
