"""Pydantic models defining the public API contracts.

These are the request/response shapes shown in Swagger and validated
automatically by FastAPI.
"""

from pydantic import BaseModel, Field


class UploadResponse(BaseModel):
    """Returned by POST /upload after a document is processed and indexed."""

    doc_id: str = Field(description="Short unique id assigned to the document")
    filename: str = Field(description="Original uploaded filename")
    category: str = Field(description="Category assigned by Agent 1")
    summary: str = Field(description="2-3 sentence summary from Agent 1")
    topics: list[str] = Field(description="Key topics detected by Agent 1")
    chunks_indexed: int = Field(description="Number of chunks stored in FAISS")
    status: str = Field(default="indexed", description="Processing status")


class AskRequest(BaseModel):
    """Body of POST /ask."""

    question: str = Field(
        min_length=1,
        description="Natural-language question about the uploaded documents",
        examples=["What skills are listed in the resume?"],
    )
    doc_id: str | None = Field(
        default=None,
        description="Optional: restrict the answer to one document",
    )


class Source(BaseModel):
    """One supporting passage used to ground the answer."""

    filename: str = Field(description="Document the passage came from")
    page: int | None = Field(default=None, description="Page number (PDFs only)")
    snippet: str = Field(description="Excerpt of the supporting text")


class AskResponse(BaseModel):
    """Returned by POST /ask."""

    answer: str = Field(description="Grounded answer generated by Agent 2")
    routed_document: str | None = Field(
        default=None,
        description="Filename Agent 2 routed the question to (None = all documents)",
    )
    sources: list[Source] = Field(description="Supporting passages")
    found: bool = Field(
        description="False when the answer is not present in the documents"
    )


class HealthResponse(BaseModel):
    """Returned by GET /health."""

    status: str = Field(description="Service status")
    documents_indexed: int = Field(description="Documents currently in the index")
