"""Pydantic models defining the public API contracts.

These are the request/response shapes shown in Swagger and validated
automatically by FastAPI.
"""

from pydantic import BaseModel, Field


class UploadResponse(BaseModel):
    """Returned by POST /upload after a document is processed and indexed."""

    doc_id: str = Field(description="Short unique id assigned to the document")
    filename: str = Field(description="Original uploaded filename")
    category: str = Field(description="Category assigned by Agent 1")
    summary: str = Field(description="2-3 sentence summary from Agent 1")
    topics: list[str] = Field(description="Key topics detected by Agent 1")
    chunks_indexed: int = Field(description="Number of chunks stored in FAISS")
    status: str = Field(default="indexed", description="Processing status")


class AskRequest(BaseModel):
    """Body of POST /ask."""

    question: str = Field(
        min_length=1,
        description="Natural-language question about the uploaded documents",
        examples=["What skills are listed in the resume?"],
    )
    doc_id: str | None = Field(
        default=None,
        description="Optional: restrict the answer to one document",
    )
    session_id: str = Field(
        default="default",
        description="Conversation session id; follow-up questions in the same "
        "session use chat history for context",
    )


class Source(BaseModel):
    """One supporting passage used to ground the answer."""

    filename: str = Field(description="Document the passage came from")
    page: int | None = Field(default=None, description="Page number (PDFs only)")
    snippet: str = Field(description="Excerpt of the supporting text")


class ValidationInfo(BaseModel):
    """Agent 3's verdict on the generated answer."""

    checked: bool = Field(description="Whether validation ran for this answer")
    supported: bool = Field(
        default=True, description="True if the answer is grounded in the context"
    )
    confidence: str = Field(
        default="unknown", description="Validator confidence: high/medium/low"
    )


class WorkflowStageInfo(BaseModel):
    """Execution record of one workflow pipeline stage."""

    name: str = Field(
        description="Stage name: observe, understand, analyze, guide, automate"
    )
    status: str = Field(description="completed, skipped, or failed")
    duration_ms: float = Field(description="Stage execution time in milliseconds")


class AskResponse(BaseModel):
    """Returned by POST /ask."""

    answer: str = Field(description="Grounded answer generated by Agent 2")
    routed_document: str | None = Field(
        default=None,
        description="Filename Agent 2 routed the question to (None = all documents)",
    )
    sources: list[Source] = Field(description="Supporting passages")
    found: bool = Field(
        description="False when the answer is not present in the documents"
    )
    validation: ValidationInfo = Field(
        default_factory=lambda: ValidationInfo(checked=False),
        description="Agent 3 grounding verdict",
    )
    workflow: list[WorkflowStageInfo] = Field(
        default_factory=list,
        description=(
            "Trace of the Observe -> Understand -> Analyze -> Guide -> "
            "Automate pipeline that produced this answer"
        ),
    )


class ScreenAnalyzeResponse(BaseModel):
    """Returned by POST /screen/analyze -- Agent 4's screen understanding."""

    application: str = Field(
        description="Application or website detected on screen"
    )
    activity: str = Field(
        description="One sentence describing what the user is doing"
    )
    detected_text: str = Field(
        description="The most important text visible on the screen"
    )
    summary: str = Field(
        description="2-3 sentence summary of what is happening on screen"
    )
    user_intent: str = Field(
        description="The user's most likely goal right now"
    )
    suggested_actions: list[str] = Field(
        description="Concrete next actions the user could take"
    )
    analysis_method: str = Field(
        description=(
            "Which pipeline produced this result: 'gemini_vision' (primary), "
            "'ocr_llm' (OCR text interpreted by the LLM), or 'ocr_only' "
            "(raw OCR text, all AI providers unavailable)"
        )
    )


class DocumentInfo(BaseModel):
    """One indexed document, as listed by GET /documents."""

    doc_id: str
    filename: str
    category: str
    summary: str
    chunks: int


class DocumentsResponse(BaseModel):
    """Returned by GET /documents."""

    documents: list[DocumentInfo]


class HealthResponse(BaseModel):
    """Returned by GET /health."""

    status: str = Field(description="Service status")
    documents_indexed: int = Field(description="Documents currently in the index")
